export const AVAILABILITY_STEP = 'StepAvailability'
export const PURCHASE_TYPE_STEP = 'StepPurchaseType'
export const FREQUENCY_SUBSCRIPTION_TYPE_STEP = 'StepFrequencySubscriptionType'
export const BOX_STEP = 'StepBox'
export const CUSTOMIZE_STEP = 'StepCustomize'
export const AUTH_STEP = 'StepAuth'
export const RESUME_ITEM_STEP = 'StepResumeItem'
export const SHIPPING_STEP = 'StepShipping'
export const DELIVERY_STEP = 'StepDelivery'
export const DELIVERY_DATE_STEP = 'StepDeliveryDate'
export const PAYMENT_STEP = 'StepPayment'

export const WEEKLY_FREQUENCY = 'weekly'
export const BIWEEKLY_FREQUENCY = 'biweekly'
export const ORDER_TYPE = 'order'
export const SUBSCRIPTION_TYPE = 'subscription'
export const HOME_DELIVERY_TYPE = 'home'
export const PICKUP_POINT_DELIVERY_TYPE = 'pickup'

export const GO_TO_STEP_EVENT = 'goToStep'
